---
# Implement your Workload removal tasks here
- name: List project namespaces
  k8s_info:
    kubeconfig: "{{ _ocp4_workload_bookbag_user_kubeconfig | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
  register: r_list_projects

- name: Remove bookbag namespace
  k8s:
    kubeconfig: "{{ _ocp4_workload_bookbag_user_kubeconfig | default(omit) }}"
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: "{{ ocp4_workload_bookbag_user_namespace }}"
  vars:
    _project_names: "{{ r_list_projects.resources | default([]) | json_query('[].metadata.name') }}"
  when: ocp4_workload_bookbag_user_namespace in _project_names

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
